users-- MySQL Script generated by MySQL Workbench
-- Thu Oct 15 10:32:10 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sound_power v1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sound_power v1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sound_power v1` DEFAULT CHARACTER SET utf8 ;
USE `sound_power v1` ;

-- -----------------------------------------------------
-- Table `sound_power v1`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sound_power v1`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `apellido` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `contraseña` VARCHAR(100) NOT NULL,
  `direccion` VARCHAR(100) NULL,
  `localidad` VARCHAR(100) NULL,
  `avatar` VARCHAR(100) NULL,
  `rol` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idUsers_UNIQUE` (`id` ASC),
  UNIQUE INDEX `contraseña_UNIQUE` (`contraseña` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sound_power v1`.`marcas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sound_power v1`.`marcas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NOT NULL,
  `imagen` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC),
  UNIQUE INDEX `imagen_UNIQUE` (`imagen` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sound_power v1`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sound_power v1`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `imagen` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idCategories_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sound_power v1`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sound_power v1`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `precio` INT UNSIGNED NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `descuento` TINYINT(100) UNSIGNED NULL,
  `imagen` VARCHAR(100) NOT NULL,
  `marca_id` INT NOT NULL,
  `categoria_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idProducts_UNIQUE` (`id` ASC),
  INDEX `marca_id_idx` (`marca_id` ASC),
  INDEX `categoria_id_idx` (`categoria_id` ASC),
  CONSTRAINT `marca_id`
    FOREIGN KEY (`marca_id`)
    REFERENCES `sound_power v1`.`marcas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `categoria_id`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `sound_power v1`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sound_power v1`.`colors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sound_power v1`.`colors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `imagen` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idcolors_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sound_power v1`.`products_colors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sound_power v1`.`products_colors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `producto_id` INT NOT NULL,
  `coloror_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `products_id_idx` (`producto_id` ASC),
  INDEX `colors_id_idx` (`coloror_id` ASC),
  CONSTRAINT `products_id`
    FOREIGN KEY (`producto_id`)
    REFERENCES `sound_power v1`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `colors_id`
    FOREIGN KEY (`coloror_id`)
    REFERENCES `sound_power v1`.`colors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sound_power v1`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sound_power v1`.`cart` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `producto_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `usuario_id_idx` (`usuario_id` ASC),
  INDEX `producto_id_idx` (`producto_id` ASC),
  CONSTRAINT `usuario_id`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `sound_power v1`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `producto_id`
    FOREIGN KEY (`producto_id`)
    REFERENCES `sound_power v1`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
